import { promises as fs } from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import ReactMarkdown from 'react-markdown';

import { SITE_URL, SITE_NAME } from '../src/config.js';

const root = process.cwd();

const postsJson = {};
const feedItems = [];

const STATIC_ROUTES = ['/', '/about', '/blogs', '/projects'];

const escapeXml = (str = '') => str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

const cdata = (str = '') => `<![CDATA[${str.replace(/]]>/g, ']]]]><![CDATA[>')}]]>`;

const template = () => `// This file is autogenerated by /scripts/compose.js, do not edit; to make changes run the compose script and/or consult the README.md (or modify if you know what you're doing)
const posts = ${JSON.stringify(postsJson)};
export default posts;`

const sitemapUrl = (loc, lastmod) => `  <url>
    <loc>${loc}</loc>${lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : ''}
  </url>`;

const buildSitemap = () => {
    const urls = STATIC_ROUTES.map((route) => sitemapUrl(`${SITE_URL}${route}`));
    for (const type of Object.keys(postsJson)) {
        for (const post of postsJson[type]) {
            if (post.draft) continue;
            const lastmod = new Date(post.dateObject).toISOString().split('T')[0];
            urls.push(sitemapUrl(`${SITE_URL}/${type}/${post.id}`, lastmod));
        }
    }
    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>
`;
}

const buildFeed = () => {
    const items = [...feedItems].sort((a, b) => b.dateObject - a.dateObject);
    const itemsXml = items.map((item) => `  <item>
    <title>${escapeXml(item.title)}</title>
    <link>${item.link}</link>
    <guid isPermaLink="true">${item.link}</guid>
    <pubDate>${item.dateObject.toUTCString()}</pubDate>
    <category>${escapeXml(item.category)}</category>
    <description>${cdata(item.summary)}</description>
    <content:encoded>${cdata(item.contentHtml)}</content:encoded>
  </item>`).join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
  <title>${escapeXml(SITE_NAME)} Blog</title>
  <link>${SITE_URL}</link>
  <atom:link href="${SITE_URL}/feed.xml" rel="self" type="application/rss+xml" />
  <description>${escapeXml(`${SITE_NAME}'s personal blog and project log`)}</description>
  <language>en-us</language>
  <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${itemsXml}
</channel>
</rss>
`;
}

const compose = async () => {
    const postsPath = path.join(root, 'src', 'posts');
    // read all the subdirectories in the posts directory
    const fileNames = await fs.readdir(postsPath, { withFileTypes: true });
    const postsList = fileNames.filter(fileName => fileName.isDirectory()).map(directory => directory.name);
    // iterate through each directory, setup up our postsJson object and go into each sub directory to create each markdown file.
    for (let index = 0; index < postsList.length; index++) {
        const postDirectoryName = postsList[index];
        const currentPostDirectory = path.join(root, 'src', 'posts', postDirectoryName);
        // get all the file from the subdirectory
        const files = await fs.readdir(currentPostDirectory);
        postsJson[postDirectoryName] = [];
        for (let i = 0; i < files.length; i++) {
            const file = files[i];
            const filePath = path.join(root, 'src', 'posts', postDirectoryName, file);
            const mdContent = await fs.readFile(filePath);
            const matterObj = matter(mdContent);
            const id = path.parse(file).name;
            const dateObject = new Date(matterObj.data.date);
            const draft = Boolean(matterObj.data.draft);
            const postJson = {
                title: matterObj.data.title,
                category: matterObj.data.category,
                date: matterObj.data.date,
                dateObject,
                path: `${postDirectoryName}/${file}`,
                id,
                draft
            }
            postsJson[postDirectoryName].push(postJson);

            if (!draft && (postDirectoryName === 'blogs' || postDirectoryName === 'projects')) {
                const contentHtml = renderToStaticMarkup(createElement(ReactMarkdown, { children: matterObj.content }));
                feedItems.push({
                    title: matterObj.data.title,
                    category: postDirectoryName,
                    link: `${SITE_URL}/${postDirectoryName}/${id}`,
                    dateObject,
                    summary: matterObj.data.summary || matterObj.data.title,
                    contentHtml,
                });
            }
        }
        postsJson[postDirectoryName].sort((a, b) => {
            return new Date(b.dateObject) - new Date(a.dateObject);
        })
    }
    const jsTemplate = template();
    const filePath = `${postsPath}/index.js`;
    await fs.writeFile(filePath, jsTemplate);

    const sitemapPath = path.join(root, 'public', 'sitemap.xml');
    await fs.writeFile(sitemapPath, buildSitemap());

    const feedPath = path.join(root, 'public', 'feed.xml');
    await fs.writeFile(feedPath, buildFeed());

    console.log("Done!");
}

compose();
